# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tribe"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chad Remesch"]
  s.date = "2012-06-10"
  s.description = "Actor Model for Ruby.  Can support millions of actors (limited by memory). Currently experimental and not recommended for production."
  s.email = "chad@remesch.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/tribe.rb",
    "lib/tribe/actor.rb",
    "lib/tribe/dispatcher.rb",
    "lib/tribe/mailbox.rb",
    "lib/tribe/message.rb",
    "lib/tribe/registry.rb",
    "lib/tribe/scheduler.rb",
    "lib/tribe/thread_pool.rb",
    "lib/tribe/timer.rb",
    "lib/tribe/worker.rb",
    "spec/lib/tribe/actor_spec.rb",
    "spec/lib/tribe/dispatcher_spec.rb",
    "spec/lib/tribe/registry_spec.rb",
    "spec/lib/tribe/scheduler_spec.rb",
    "spec/lib/tribe/timer_spec.rb",
    "spec/lib/tribe/worker_spec.rb",
    "spec/spec_helper.rb",
    "tribe.gemspec"
  ]
  s.homepage = "http://github.com/chadrem/tribe"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Actor Model for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_development_dependency(%q<guard>, ["~> 1.1.1"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 1.0.0"])
      s.add_development_dependency(%q<growl>, [">= 0"])
      s.add_development_dependency(%q<debugger>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_dependency(%q<guard>, ["~> 1.1.1"])
      s.add_dependency(%q<guard-rspec>, ["~> 1.0.0"])
      s.add_dependency(%q<growl>, [">= 0"])
      s.add_dependency(%q<debugger>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, ["~> 2.10.0"])
    s.add_dependency(%q<bundler>, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, [">= 0"])
    s.add_dependency(%q<guard>, ["~> 1.1.1"])
    s.add_dependency(%q<guard-rspec>, ["~> 1.0.0"])
    s.add_dependency(%q<growl>, [">= 0"])
    s.add_dependency(%q<debugger>, [">= 0"])
  end
end

